# Generated by Django 5.1.3 on 2024-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='')),
                ('Price', models.IntegerField()),
                ('Qty', models.IntegerField()),
            ],
            options={
                'db_table': 'table_toy',
            },
        ),
    ]
