# Generated by Django 5.1.3 on 2024-11-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='id',
            new_name='Id',
        ),
    ]
