# Generated by Django 5.1.3 on 2024-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy', '0002_rename_id_toy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='Image',
            field=models.CharField(max_length=200),
        ),
    ]
